<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Cookie\Middleware\EncryptCookies as Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cookie;

class EncryptCookies extends Middleware
{
    /**
     * The names of the cookies that should not be encrypted.
     *
     * @var array
     */
    protected $except = [
        //
    ];
    public function handle($request, Closure $next)
    {
        if (!Auth::check()) {
            $userId = Cookie::get("guest_id");
            if (is_null($userId)) {
                $key = time() . rand();
                Cookie::queue("guest_id",$key,800);
            }

        }

        return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }
}
